FROM node:20

WORKDIR /home/node/app

COPY package*.json ./

ARG API_URL
ARG SESSION_SECRET 
ARG AWS_BUCKET_NAME
ARG SESSION_MAX_AGE

ENV API_URL ${API_URL}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV SESSION_MAX_AGE ${SESSION_MAX_AGE}

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]