FROM node:20

WORKDIR /home/node/app

COPY package*.json ./

ARG API_URL
ARG SESSION_SECRET 
ARG AWS_BUCKET_NAME
ARG SESSION_MAX_AGE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV API_URL ${API_URL}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV SESSION_MAX_AGE ${SESSION_MAX_AGE}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]