name: Nightly Pa11y Accessibility Tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Pa11y CI tests
        run: npx pa11y-ci